# Created by: Mike English <mike.english@gmail.com>
# $FreeBSD$

PORTNAME=	ka9q-radio
PORTVERSION=	0.0.1
CATEGORIES=	comms hamradio

MAINTAINER=	mike.english@gmail.com
COMMENT=	A set of SDR modules connected by Internet RTP and IP Multicast for experimentation

LICENSE=	GPLv3

USE_GITHUB=	yes
GH_ACCOUNT=	phase4ground
GH_PROJECT=	ka9q-radio

.include <bsd.port.mk>
